### PR TITLE
Hw 18

### PR DESCRIPTION
**Pull request by Rana310**
ohhhh!!
I forget to open pull request when i pushed it!!
You can check my repo! 
thank you :-)

### CODE REVIEW

**Review by EliasSalom — APPROVED** [review]
Good work

**Comment by EliasSalom** [comment]
Rana, there are some `Conflicting files` in `README.md` please find them and make a new push and pull request

**Comment by Rana310** [comment]
I Solve the problem with Conflicting files

**Review by EliasSalom — APPROVED** [review]
Good work

**Pull request merged**
